provide a saver was to write to the log file when many concurrent …
productsupcom/flexilog pull request #17
Opened 2017-11-10 11:18 UTC by wernerspiegelpup

… processes write to the same file

2017-11-10 11:22 UTC, 0bp requested changes

2017-11-10 11:22 UTC, 0bp commented on lib/Handler/FileHandler.php
> +        if ((!file_exists($filename) && file_put_contents($filename, '') === false) || !is_writable($filename)) {
Dangerous as `file_put_contents($filename, '')` would immediately overwrite the file.

2017-11-10 12:09 UTC, terwey commented on lib/Handler/FileHandler.php
> +            throw new HandlerException('Cannot write to file: ' . $this->filename);
Not needed, returning `false` is enough. The exception should be thrown a level higher (as it's already done).

2021-03-23 12:37 UTC, r4ndsen commented
apparently irrelevant

2021-03-23 12:37 UTC, closed without merging